### ISSUE TITLE
Establish a Github-based workflow for coordinated model development between teams

### ISSUE THREAD

**Issue by bfurner** [cancerDHC/data-model-harmonization#10]
Once we have settled on a language and framework, this will allow for our work to be transparent and immediately reviewable by the community - so it can evolve in an iterative, efficient and well-documented manner.

**Comment by monicacecilia** [comment]
A kind reminder that _Establish a Github-based workflow for coordinated development between teams_ is meant to be issued for review by CRDC community, and it is meant to happen during Q4 2020 and Q1 2021. 
Just making sure this is still on your radar. 
@bfurner 👀 ⬆️

**Comment by bfurner** [comment]
The workflow isn't meant to be issued for review by the CRDC community.  This is an internal workflow between the workstreams in CCDH.  The scripting to generate LinkML artifacts from the CDM was originally authored by @jiaola but I believe @gaurav has picked up some of this work since.

**Comment by gaurav** [comment]
Yup! I've started pulling down a little example data at http://github.com/cancerDHC/example-data (https://github.com/cancerDHC/tools/issues/27). This week I'll work on validating that against a LinkML model (https://github.com/cancerDHC/tools/issues/32) and building a runner to validate the example data against it (https://github.com/cancerDHC/tools/issues/29). Eventually, I think it would also be good to automatically build the LinkML model from the Google Sheet whenever we carry out validation (https://github.com/cancerDHC/tools/issues/32). I think that will meet the requirements of this issue.

**Comment by bfurner** [comment]
This is great.  Thanks so much @gaurav

**Comment by bfurner** [comment]
For the purposes of Phase II this work is considered complete.  Thanks to efforts from Gaurav, Dazhi, and the model harmonization team, we have an effective and functional process that goes from curation in google sheets, to LinkML model description yaml files, into LinkML python classes and model documentation, along with consuming terminologies from the TCCM.
