### ISSUE TITLE
Establish a system (resources, processes, roles) for keeping SSDs, ADM, and CDM in sync with upstream node models

### ISSUE THREAD

**Issue by bfurner** [cancerDHC/data-model-harmonization#11]
- [x] reach out to model reps from each source to understand how often they update model, how changes are documented, preferences for how to communicate this to us
- [x] bring this info back to the team so we can propose a systematic approach that will work across sources

**Comment by bfurner** [comment]
From Resham: 

"I’m following up on our conversation during the meeting regarding how CCDH and CDA would like to get notified about data model changes. Here is what would be good to have from your side.
 
It will be good for CCDH and CDA to coordinate on 
- how you would like to get the changes Nodes make to their Data Model (is there anything you would need to develop on your end?)
- what type of communications will be useful
- it will be good to define what is a must have and what is nice to have
 
We can convey back to the nodes, and they can establish communication plans to match your requirements."

**Comment by monicacecilia** [comment]
Also from Resham: 
- Proposal: requirements from CCDH/CDA could be first relayed to ICDC and CTDC. They would work with you to establish a communications plan on their side that meets your requirements, once established this could then be shared with and suggested to other nodes.

**Comment by bfurner** [comment]
So we should propose something that works for us and gather feedback.  

We need to determine:

1) what information we need from sources (e.g. granular and computable change log so we know what needs to be altered on our end)
2) what format and shape we want this information presented to us (e.g. JSON in some TBD schema)
3) when we want to receive that information (e.g. only when changes move to production?  Before then?)
4) how we want to receive this information (e.g. email notifications? slack? push to some TBD endpoint?)

**Comment by bfurner** [comment]
Link to SOP document produced by Maura and Anne: [SOP link](https://docs.google.com/document/d/17NJtBHA0uq_G8AyydsYTXlSO4Nmjz7sXMt5H0PAk1nY/edit#heading=h.i20vp3e0a1i5)

**Comment by bfurner** [comment]
Link to initial proposal for [changelog](https://docs.google.com/spreadsheets/d/1W83V_EjQzD9e5nQ4EBR8keC1LZqnB49kK0bj15p78xo/edit#gid=0)

**Comment by bfurner** [comment]
SOP and proposed changelog completed.  The next iteration of this work should include pulling model changes directly from source repos where possible rather than relying on sources to notify us through a changelog.
