### ISSUE TITLE
Agree on queries

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/data-model-harmonization#21]
Agree on queries with CDA that meet the following criteria:

**Comment by mellybelly** [comment]
Some criteria for deciding:
- high priority by CDA
- requires multiple nodes' data
- there is enough data within each node to generate an interesting query results
- the queries take advantage of the new metadata elements identified by the metadata DST
- the queries will require data from multiple nodes that we know is present in them
- The selected query should contain some “challenging” data elements. Having a query that consists of only non-enumerated data elements or “easy” enumerated data elements would not be as informative.

**Comment by monicacecilia** [comment]
Added above -- 
The selected query should contain some “challenging” data elements.  Having a query that consists of only non-enumerated data elements or “easy” enumerated data elements would not be as informative.
(from Robinette)

**Comment by monicacecilia** [comment]
Update from KathyR: 

> There are 10 queries (of 11) that seem appropriate for the CCDH pilot on the Release 2 Queries tab.  See Column entitled 'Use for DST Pilot'.  Elijah is verifying the queries and will add notes to this column as he verifies that there is data across the 3 nodes for the query.  (Note that we will add queries for Release 2 and add notes as we continue towards our Release 2 deliverable.

(if needed, request access to Queries file from members of the DMH team)

**Comment by bfurner** [comment]
The queries we executed were 

D1 Query: "Find frozen Osteosarcoma tumor specimens >30 mg that are lung metastases from patients with Stage 4 disease"
D2 Query: "Find patients in the TCGA-OV project who are 50 years of age or older and who have Stage IIIC ovarian cancer"
