### ISSUE TITLE
Properties and data types to hold identifiers

### ISSUE THREAD

**Issue by mbrush** [cancerDHC/data-model-harmonization#5]
Many ADM entities have different properties to hold different types of identifiers.  
- e.g. **PDC.Sample** has an _sample_id_, _sample_submitter_id,_ and _gdc_sample_id_. 
- e.g. **PDC.Sample** has a _project_id_ and a _gdc_project_id_.

We should define and consistently apply a standard and principled way to capture multiple identifiers for an entity instance.

**Some options:**
  
1. **Create separate properties for each type of identifier** (meaning of identifier type baked in)
    a. This is the current approach taken by CRDC node models - e.g. pdc.Sample has 'sample_id', 'gdc_sample_id', and 'sample_submitter_id'. 
    b. But I think is only scalable if there is a small and finite number of possible identifiers that users may want to create.

2. **Use a single 'identifier' field that takes a complex identifier data types, holding a field to specify the type of identifier** 
    a. This is more flexible and extensible.  It is how BRIDG does things, using its "II" data type which allows you to capture the type of the identifier. 
    b. It is very flexible, but produces data where the actual identifier for an instnace is nested, and thus the data may be harder to parse.
3. **Limit to two and only two identifier properties ('business' id and 'logical' id)**
    a. One holds 1..1 'logical' identifier that is captured directly as a string (the unique id of the entity in the system of record, e.g. a UUID)
    b. Another can hold 0..m 'business' ids - identifiers provided by any number of external systems, captured as a complex identifier data type (where the source system / agent for the identifier can be captured)
    c. This makes the primary logical identifier easy to find and parse. It limits potential for proliferation of identifier properties. This is how FHIR does things. 
    d. For external/business identifiers, we may need to have some field in the complex identifier data type to capture identifier provider role (e.g. as a submitter)

**Comment by bfurner** [comment]
@mbrush Would you consider this done in that we appear to have opted for approach 2 in our Biolink representation (https://github.com/cancerDHC/ccdhmodel/blob/mvpv0/model/datatypes.yaml#L17-L31)??

**Comment by mbrush** [comment]
@bfurner I think we can close it, as we have committed to an approach for our initial model.  Can always re-open the ticket if we decide to revisit other options.    However, I want to be clear that it is option 3 above that we went with, not option 2 - and make sure you are ok with this Brian.

**Comment by bfurner** [comment]
yes, correct that we went with option 3.  sorry for my mistake there.  thanks
