### ISSUE TITLE
Decide on formal implementation language/framework for CRDC-H

### ISSUE THREAD

**Issue by bfurner** [cancerDHC/data-model-harmonization#9]
- [x] Work with nodes and CDA to make decisions - Cara/Moni will coordinate to set time for a meeting in the next couple weeks?

- [x] First step is to define and evaluate our options. We will start a doc with sections for each possible approach, where people can start adding notes on pros and cons in different categories (AI for Shahim)

**Comment by bfurner** [comment]
- [ ] Work with nodes and CDA to make decisions - Cara/Moni will coordinate to set time for a meeting in the next couple weeks?

- [ ] First step is to define and evaluate our options. We will start a doc with sections for each possible approach, where people can start adding notes on pros and cons in different categories (AI for Shahim)

**Comment by mbrush** [comment]
Adding the notes we took during the 7-2-20 DMH Call about modeling language options to evaluate, and possible criteria for evaluation. These may be useful for seeding the Google doc we will use for this work.

**Modeling Language Options:**

- FHIR ML
- FHIR IG
- UML
- Biolink ML
- JSON-schema based DDL (i.e. a superset of json schema language - similar to some of the bespoke mode modeling languages)
- Node modeling languages/formats (e.g. Bento/MDF)
- CDA’s modeling language

------

**Possible Evaluation Criteria:**

- entity representation
- support for inheritance?
- relationships (binary, vs richer associations)
- property representations
- data type representation
- query support (e.g. FHIR spec supports keywords standing for complex query paths - they define how queries work)
- support for representing mappings (between resources, fields, value sets)
- support for representing value sets, and services around them
- API support
- associated tooling
     - for transformations between representation languages
     - for publishing the model

**Comment by bfurner** [comment]
Link to the document that enumerates the options and pors/cons here: [Document](https://docs.google.com/document/d/1WICqwfB-czRk1CJ9cDtN56vJCcNTSJzlNIPwkWr1Jgg/edit#)

**Comment by bfurner** [comment]
The data model harmonization workstream will be making us of biolinkml as the language in which to express its model for the initial MVP work with the CDA.  We will evaluate this decision at the end of the MVP work
